package io.github.monthalcantara.casadocodigo.entity;

import lombok.Getter;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.Email;
import java.time.LocalDateTime;

@Getter
@NoArgsConstructor
//@DynamoDBTable(tableName = "Autores")
@Entity
public class AutorEntity {

    //        @DynamoDBHashKey
//        @DynamoDBAutoGeneratedKey
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    //        @DynamoDBAttribute
    private String nome;

    //        @DynamoDBAttribute
    private String email;

    //        @DynamoDBAttribute
    private String descricao;

    // @DynamoDBAttribute
    private LocalDateTime instanteCriacao;

    public AutorEntity(String nome, String email, String descricao, LocalDateTime instanteCriacao) {
        this.nome = nome;
        this.email = email;
        this.descricao = descricao;
        this.instanteCriacao = instanteCriacao;
    }
}
