version: '3.5'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data
