
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true