version: '3'

services:
  mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_USERNAME: "root"
    ports:
      - "3306:3306"
    volumes:
      - apicdc_data:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge
volumes:
  apicdc_data: