version: '3'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:0.10.7
    network_mode: bridge
    ports:
      - "4576:4576"
      - "8080:8080"
    environment:
      - DEFAULT_REGION=us-east-1
      - SERVICES=sqs
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"