version: '3.7'

services:
  localstack:
#    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:0.10.7
    network_mode: bridge
    ports:
      - "4566:4566"
      - "8000:8000"
    environment:
      - DEFAULT_REGION=us-east-1
      - SERVICES=dynamoDB
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"