version: "3.8"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:0.11.2
    ports:
      - "4566-4599:4566-4599"
    volumes:
      - ./local:/docker-entrypoint-initaws.d
      
